### ISSUE TITLE
Create common figures via context menu

### ISSUE THREAD

**Issue by stevenschwenke** [tinosteinort/gameoflife#1]
It would be great to create common figures like the glider via context menu at a given location. This way, the behavior of GoL could be explained more easily.
In a simple implementation, the orientation of those figures could be neglected. However it would be cool to give a direction to the glider. Imagine two opposite gliders coliding with each other. :D

**Comment by tinosteinort** [comment]
The simple part of the implementation is done: now it is possible to create a Glider, LWSS, MWSS and a HWSS via context menu

**Comment by tinosteinort** [comment]
No it is possible to edit the direction of the figure :-)
